import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import FadeIn from "react-fade-in";
import useGame from "../game/useGame";
import { maxScore } from "../game/gameReducer";

const Options = ({ options, onChooseResponse }) => {
  return (
    <ul
      style={{
        display: "flex",
        width: "100%",
        flexWrap: "wrap",
        listStyle: "none",
        justifyContent: "space-evenly",
        color: "rgb(255,251,235)",
      }}
    >
      {options.map((option, index) => (
        <li
          key={`${index}`}
          onClick={() => onChooseResponse(index)}
          className={styles.option}
        >
          {option.text}
        </li>
      ))}
    </ul>
  );
};

const Story = ({ score, maxScore }) => {
  return (
    <div
      style={{
        position: "relative",
        height: "150px",
        width: "1000px",
        background: "rgb(2,0,36)",
        background:
          "linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(21,116,90,1) 47%, rgba(3,100,111,1) 100%)",
        borderBottom: "10px solid rgb(15,23,42)",
      }}
    >
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: "50px",
          height: "0px",
          width: "900px",
          borderTop: "5px dotted yellow",
        }}
      />

      <div
        style={{
          position: "absolute",
          bottom: "-20px",
          left: `calc(-30px + (900px / 6) * ${Math.min(
            Math.max(0, score),
            maxScore
          )})`,
          zIndex: 10,
          opacity: score < 0 || score > maxScore ? 0.3 : 1,
        }}
      >
        <Image src="/noun-bear.svg" alt="Bear" width={160} height={160} />
      </div>

      {Array.from(Array(maxScore + 1).keys()).map((index) => (
        <div
          key={index}
          className={styles.circle}
          style={{
            left: `calc(35px + (900px / 6) * ${index})`,
          }}
        />
      ))}
    </div>
  );
};

export default function Home() {
  const [gameState, { chooseResponse, restart }] = useGame();

  const { dialogue, previousOptions, gameOver, gameWon, finalText, score } =
    gameState;

  const onChooseResponse = (optionIndex = 0) => {
    chooseResponse(optionIndex);
  };

  const handleRestart = () => {
    restart();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>I Will Eat You | Change My Mind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleRestart}>Restart</button>

        <Story score={score} maxScore={maxScore} />
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            width: "1000px",

            // backgroundColor: "lightblue",
            position: "relative",
            color: "black",
            justifyContent: "center",
            alignItems: "center",
            color: "rgb(252,211,77)",
          }}
        >
          {gameWon ? (
            <>
              <div>
                {finalText.split("\n").map((text, index) => (
                  <p key={`${index}`}>{text.trim()}</p>
                ))}
              </div>
              <Image
                src="/noun-grizzly-bear_stand.svg"
                height={400}
                width={400}
                alt="Bear"
              />
              <big>{`I think I might go try to get some food. 

                You can go home now.`}</big>
            </>
          ) : gameOver ? (
            <>
              <div>
                {finalText.split("\n").map((text, index) => (
                  <p key={`${index}`}>{text.trim()}</p>
                ))}
              </div>
              <Image
                src="/noun-bear_scare.svg"
                height={400}
                width={400}
                alt="Attacking bear"
              />
              <big>*eats you*</big>
            </>
          ) : (
            <>
              <div
                style={{
                  // position: "absolute",
                  height: "500px",
                  width: "1000px",
                  // backgroundColor: "pink",
                  color: "rgb(252,211,77)",
                }}
              >
                <div style={{ color: "rgb(255,251,235)" }}>
                  <FadeIn>
                    {(dialogue.text ?? "").split("\n").map((text, index) => (
                      <p key={`${index}`}>{text.trim()}</p>
                    ))}
                  </FadeIn>
                </div>

                <div
                  style={{
                    backgroundColor: "transparent",
                    color: "rgb(252,211,77)",
                  }}
                >
                  <FadeIn>
                    {dialogue.response.text.split("\n").map((text, index) => (
                      <p key={`${index}`}>{text}</p>
                    ))}
                  </FadeIn>
                </div>

                <Options
                  options={
                    dialogue.response.options?.length
                      ? dialogue.response.options
                      : previousOptions
                  }
                  onChooseResponse={onChooseResponse}
                />
              </div>
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
